apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
data:
  portal-config.yaml: |
    {{- if .Values.console.portalConfig }}
    {{- .Values.console.portalConfig | nindent 4}}
    {{- else}}
    {{- tpl (.Files.Get "scripts/console/portal-config.yaml") . | nindent 4 }}
    {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: home-config
data:
  home-config.yaml: |
    {{- if .Values.console.homeConfig }}
    {{- .Values.console.homeConfig | nindent 4}}
    {{- else}}
    {{- tpl (.Files.Get "scripts/console/home-config.yaml") . | nindent 4 }}
    {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-default-covers
binaryData:
{{- $root := . }}
{{- range $path, $bytes := .Files.Glob "scripts/console/covers/*" }}
  {{ base $path }}: |-
    {{ $root.Files.Get $path | b64enc }}
{{- end }}

