---
# This values yaml is for ee installation
#
# Usage:
#   helm install primehub infuseai/primehub -f ee-values.yaml -f user-override.yaml

primehub:
  mode: ee

customImage:
  enabled: true

store:
  enabled: true
  phfs:
    enabled: true
  logPersistence:
    enabled: false

jobSubmission:
  enabled: true
  artifact:
    enabled: true

usage:
  enabled: false

modelDeployment:
  enabled: true

adminNotebook:
  enabled: false

controller:
  image:
    tag: sc-28495-290ef5